name: CI/CD Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VDS_SSH_KEY }}

      - name: Verify SSH Key
        run: ssh-add -l

      - name: Deploy to VDS
        env:
          VDS_USER: ${{ secrets.VDS_USER }}
          VDS_IP: ${{ secrets.VDS_IP }}
          VDS_PROJECT_DIR: ${{ secrets.VDS_PROJECT_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $VDS_USER@$VDS_IP << 'EOF'
            mkdir -p /home/bot/landing
            cd /home/bot/landing
            if [ ! -d ".git" ]; then
              git clone git@github.com:BaseOfBot/landing.git .
            else
              git pull origin main
            fi
            docker-compose -f ./.docker/remote/docker-compose.yml down && \
            docker-compose -f ./.docker/remote/docker-compose.yml up -d --build
          EOF
